  name: ServerAntiVPN
  main: rip.snake.antivpn.spigot.ServerAntiVPN
  version: ${project.version}
  api-version: 1.13
  softdepend:
    - ViaVersion
  commands:
    antivpn:
      description: ServerAntiVPN command
      aliases: [savpn]
      permission: antivpn.command
      usage: /<command> [token]